# # # # # # # # # # # # #
#   K i k o - p l u s   #
# # # # # # # # # # # # #

# Basic
name: "GeoWanderer"

author:
  facebook:
  youtubeUser:
  youtubeChannel:
  twitter: Griegite           
  github: kjmanion
  stackoverflow:
  quora:
  linkedin:         
  pinterest:
  googlePlus:
  instagram:
  reddit:
  medium:
  tumblr:
  email:

collections:
  portfolio:
    output: true
   


copyright:
  year: 2019
  name: 

# Google-analytics
google-analytics:
  id: ""

# Disqus
disqus:
  id: ""

# URL
url: "https://kevinmanion.com" # the base hostname & protocol for your site
# url:                "http://localhost:4000" # use this url when you develop
baseurl: "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/New_York
permalink: /:year-:month-:day/:title/

# Pagination
paginate: 5
paginate_path: /page:num/

# Markdown
markdown: kramdown
kramdown:
  input: GFM

# Navigation
nav:
  - name: "About"
    url: "/about"
  - name: "Portfolio"
    url: "/portfolio/"
  - name: "Archive"
    url: "/archive"
  - name: "Tags"
    url: "/tags"
  - name: "Github"
    url: "https://github.com/kjmanion"
  

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Scopes
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "portfolios"
    values:
      layout: "page"


# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude: [vendor]
